CREATE TABLE Alunos (
    AlunosID int,
    PrimeiroNome varchar(255),
    Sobrenome varchar(255),
    Idade varchar(255)
);

INSERT INTO Alunos (ID, nome, sobrenome, idade)
VALUES
(1,'Alice', 'Campos', 17),
(2, 'Adrielly', 'Inocencio', 17),
(3, 'Andrey', 'Sousa Tristão', 17),
(4, 'Annely Leticia', 'moreira carrero', 16),
(5, 'Caroline Camargo', 'da Silva', 16),
(6, 'Daiana Ferreira', 'dos Santos', 18),
(7, 'Emmily', 'Oliveira de Souza', 17),
(8, 'Enzo', 'Ferreira dos Santos', 16),
(9, 'Evelyn dos', 'Santos Moura', 17),
(10, 'Gabriela', 'Boarati Macedo', 16),
(11, 'Gabriel Moreira', 'dos Reis Barbosa', 17),
(12, 'Geovana Ferreira', 'Vieira', 16),
(13, 'Geovanna da', 'Silva Nascimento', 17),
(14, 'Gustavo Isaac Argentino', 'da Silva', 17),
(15, 'Heloisa', 'Oliveira Nunes', 17),
(16, 'Hugo', 'Romoda', 18),
(17, 'Isabella Bertolo', 'dos Santos', 17),
(18, 'Isabella Maria', 'Assis Patricio', 17),
(19, 'Isadora da Silva', 'Souza Silveira', 17),
(20, 'Isabella', 'almeida dos santos', 17),
(21, 'João Guilherme Marcondes', 'da Silva', 17),
(22, 'Livia Macedo', 'de Oliveira', 17),
(23, 'Milleny da', 'Silva Leopoldino', 17),
(24, 'Ollyver', 'Osório', 18),
(25, 'Pedro Arthur', 'Pizarro', 17),
(26, 'Pietra Alberganti', 'Basso', 16),
(27, 'Ryan Brandão', 'dos Santos', 18),
(28, 'Thiago Lima', 'Silva', 17),
(29, 'Vitor Hugo Alves', 'Basso', 16),
(30, 'Victor dos Santos', 'Calori', 16),
(31, 'Vinicius Rickelme Pavani', 'de Souza', 17),
(32, 'Wesley', 'Batista', 17);
